name: Build and Test
on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  unit: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Unit Test
        run: go test ./pkg/... -cover -tags=test
  
  ci:
    runs-on: ubuntu-latest
    env:
      ARCH: amd64
      CACHE_ARGS: "--cache-from=type=local,src=$RUNNER_TEMP/.buildx-cache --cache-to=type=local,dest=$RUNNER_TEMP/.buildx-cache-new,mode=max"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-pr-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-buildx-pr

      - name: Build binary
        run: make build CACHE_ARGS=${CACHE_ARGS}
    
      - name: Validate
        run: make validate CACHE_ARGS=${CACHE_ARGS}
      
      - name: Package
        run: make package

      - name: E2E Test
        run: ./scripts/e2e

      - name: Move cache
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache