name: Build and Test
on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  unit: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Unit Test
        run: go test ./pkg/... -cover -tags=test
  
  ci:
    runs-on: ubuntu-latest
    env:
      ARCH: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build binary
        run: |
          make build \
            CACHE_ARGS="--cache-from=type=gha --cache-to=type=gha,mode=max,scope=build,ghtoken=${{ secrets.GITHUB_TOKEN }}" \
            BUILDX="buildx"
    
      - name: Validate
        run: |
          make validate \
            CACHE_ARGS="--cache-from=type=gha --cache-to=type=gha,mode=max,scope=validate,ghtoken=${{ secrets.GITHUB_TOKEN }}" \
            BUILDX="buildx"
      
      - name: Package
        run: make package

      - name: E2E Test
        run: ./scripts/e2e
